name: Minigolf
version: '${project.version}'
main: spinalcraft.minigolf.Minigolf
api-version: 1.20
authors: [Belinski20]
description: Minigolf
depend: [Vault]

commands:
  mgcard:
    permission-message: Do not have valid permissions to use
    usage: /mgcard
    description: shows the players ScoreCard
    permission: minigolf.mgcard
  start:
    permission-message: Do not have valid permissions to use
    usage: /start <Player Name> <Course Name>
    description: Starts minigolf for a specified course
    permission: minigolf.start
  party:
    permission-message: Do not have valid permissions to use
    usage: /party <invite | list | accept | reject | leave>
    description: Makes a party for golf
    permission: minigolf.party
  cc:
    permission-message: Do not have valid permissions to use
    usage: /cc <new | edit | save | quit | green>
    description: Used to create and edit courses
    permission: minigolf.cc
  mgcosmetic:
    permission-message: Do not have valid permissions to use
    usage: /mgcosmetic <Player Name> <ball | club> <Material>
    description: Used to change club and ball skins
    permission: minigolf.cosmetics